[program:scheduler]
command=/bin/sh -c "while [ true ]; do (php /work/artisan schedule:run --verbose --no-interaction &); sleep 60; done"
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

