events {
    worker_connections  4096;  ## Default: 1024
}

http {
    include     /etc/nginx/mime.types;

    large_client_header_buffers 4 256k;

    gzip            on;
    gzip_vary       on;
    gzip_static     on;
    gzip_types      text/plain
                    text/css
                    text/xml
                    text/javascript
                    application/json
                    application/javascript
                    application/xml
                    application/xhtml+xml
                    application/rss+xml
                    application/x-javascript
                    application/atom+xml
                    application/x-httpd-php;
    gzip_buffers    4 8k;
    gzip_disable    "msie6";
    gzip_proxied    any;
    gzip_comp_level 9;

    server {
        server_name giangthe.local;
        listen          80;             # the port nginx is listening on

        gzip            on;
        gzip_types      text/plain application/xml text/css application/javascript;
        gzip_min_length 1000;

        charset utf-8;

        root /frontend/online;

        location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|otf|ttf|svg|js|css)$ {
            add_header Pragma public;
            add_header Cache-Control "public";

            try_files $uri $uri/;
        }

        location / {

            try_files $uri $uri/ /index.html;
        }

        #### API ####
        location /api {

            alias /work/public; #preferred over root
            index  index.php;
            # @api is a named location
            try_files $uri $uri/ @api;

            location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass giangthe_site:9000;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $request_filename;
            }
        }

        location @api {
            rewrite /api/(.*)$ /api/index.php?$query_string;
        }

        #### FILES ####
        location /storage {
            alias /work/public/storage; #preferred over root
        }
    }
}
