[program:emails]
process_name=%(program_name)s_%(process_num)02d
command=php /work/artisan queue:work --queue=emails --sleep=3 --tries=3 --daemon
autostart=true
autorestart=true
numprocs=4
user=root
redirect_stderr=true
stdout_logfile=/var/log/worker_email.log
